version: "3"
services:
  db:
    image: postgres:10.8-alpine
    ports:
        - 5432:5432
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    env_file: .env
  api:
    build: .
    env_file:
      - .env
    ports:
      - 8080:80
    devices:
      - /dev/video0:/dev/video0